leftnav:
- identifier: 0409a406-eed4-47c2-b12f-3d8e6afcff44
  name: "Teaching Marguerite de Navarre's Heptam\xE9ron Website"
  pageRef: "/external-resources/teaching-marguerite-de-navarres-heptam\xE9ron-website_0409a406-eed4-47c2-b12f-3d8e6afcff44"
  weight: 10
